# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [33]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([0,1,2,3,4,5,6,7,8,9])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([
    [0,1,2,3,4],
    [5,6,7,8,9],
])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [
        [0,1,2,3,4],
        [5,6,7,8,9]
    ],
    [
        [1,2,3,4,5],
        [6,7,8,9,0]
    ],
    [
        [2,3,4,5,6],
        [7,8,9,0,1]
    ]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [34]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1
a1.dtype, type(a1), a1.ndim, a1.size, a1.shape

(dtype('int32'), numpy.ndarray, 1, 10, (10,))

In [36]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
# Attributes of 2-dimensional array
a2
a2.dtype, type(a2), a2.ndim, a2.size, a2.shape

(dtype('int32'), numpy.ndarray, 2, 10, (2, 5))

In [38]:
a3

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]],

       [[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]],

       [[2, 3, 4, 5, 6],
        [7, 8, 9, 0, 1]]])

In [39]:
# Attributes of 3-dimensional array
a3
a3.dtype, type(a3), a3.ndim, a3.size, a3.shape

(dtype('int32'), numpy.ndarray, 3, 30, (3, 2, 5))

In [47]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)

In [48]:
df

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [44]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))

In [45]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))

In [50]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [56]:
# Create an array within a range of 0 and 100 with step 3
a4_range = np.arange(0,100,3)

In [58]:
a4_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [61]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5_random = np.random.randint(0,11,size=(7,2))

In [62]:
a5_random

array([[ 9,  1],
       [ 7,  1],
       [ 7,  8],
       [ 8,  4],
       [10,  0],
       [ 7,  1],
       [ 6,  6]])

In [65]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6_random = np.random.random((3,5))

In [66]:
a6_random

array([[0.33019328, 0.7491465 , 0.76017024, 0.8953222 , 0.95831363],
       [0.7237242 , 0.29431878, 0.56703733, 0.2261851 , 0.11686211],
       [0.69243277, 0.92254032, 0.14862569, 0.92457179, 0.22959348]])

In [67]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a7_random = np.random.randint(0,11,size=(4,6))

In [74]:
a7_random

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [86]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a8_random = np.random.randint(1,11,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(a8_random)

array([ 1,  2,  3,  4,  7,  8,  9, 10])

In [87]:
a8_random

array([[ 3,  4,  7,  4,  9,  1,  8],
       [ 7,  2,  8,  1,  9,  9,  2],
       [ 7, 10,  3,  7, 10,  9,  4]])

In [89]:
# Find the 0'th index of the latest array you created
a8_random[0]

array([3, 4, 7, 4, 9, 1, 8])

In [90]:
# Get the first 2 rows of latest array you created
a8_random[:2]

array([[3, 4, 7, 4, 9, 1, 8],
       [7, 2, 8, 1, 9, 9, 2]])

In [92]:
# Get the first 2 values of the first 2 rows of the latest array
a8_random[:2,:2]

array([[3, 4],
       [7, 2]])

In [93]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a9_random = np.random.randint(0,11,size=(3,5))
a10_ones = np.ones((3,5))

In [95]:
a9_random

array([[ 0,  1,  0,  4,  4],
       [10,  6,  8,  8,  2],
       [ 2,  2,  3,  7,  5]])

In [94]:
a10_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
# Add the two arrays together
a9_random + a10_ones

array([[ 1.,  2.,  1.,  5.,  5.],
       [11.,  7.,  9.,  9.,  3.],
       [ 3.,  3.,  4.,  8.,  6.]])

In [97]:
# Create another array of ones of shape (5, 3)
a11_ones = np.ones((5,3))

In [98]:
a11_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
# Try add the array of ones and the other most recent array together
a10_ones + a11_ones.T

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [100]:
# Create another array of ones of shape (3, 5)
a12_ones = np.ones((3,5))

In [101]:
a12_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [106]:
# Subtract the new array of ones from the other most recent array
a11_ones.T - a12_ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [108]:
# Multiply the ones array with the latest array
a12_ones * a11_ones.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
# Take the latest array to the power of 2 using '**'
a12_ones ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [111]:
a9_random ** 2

array([[  0,   1,   0,  16,  16],
       [100,  36,  64,  64,   4],
       [  4,   4,   9,  49,  25]], dtype=int32)

In [110]:
# Do the same thing with np.square()
np.square(a12_ones)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
# Find the mean of the latest array using np.mean()
np.mean(a9_random)

4.133333333333334

In [113]:
# Find the maximum of the latest array using np.max()
np.max(a9_random)

10

In [114]:
# Find the minimum of the latest array using np.min()
np.min(a9_random)

0

In [115]:
# Find the standard deviation of the latest array
np.std(a9_random)

3.0081371127142607

In [116]:
# Find the variance of the latest array
np.var(a9_random)

9.048888888888888

In [117]:
a9_random

array([[ 0,  1,  0,  4,  4],
       [10,  6,  8,  8,  2],
       [ 2,  2,  3,  7,  5]])

In [119]:
# Reshape the latest array to (3, 5, 1)
np.reshape(a9_random,(3,5,1))

array([[[ 0],
        [ 1],
        [ 0],
        [ 4],
        [ 4]],

       [[10],
        [ 6],
        [ 8],
        [ 8],
        [ 2]],

       [[ 2],
        [ 2],
        [ 3],
        [ 7],
        [ 5]]])

In [120]:
# Transpose the latest array
a9_random.T

array([[ 0, 10,  2],
       [ 1,  6,  2],
       [ 0,  8,  3],
       [ 4,  8,  7],
       [ 4,  2,  5]])

What does the transpose do?

In [124]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(0)
a13_random = np.random.randint(0,11,size=(3,3))
a14_random = np.random.randint(0,11,size=(3,2))

In [125]:
a13_random

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [123]:
a14_random

array([[7, 3],
       [2, 8],
       [2, 8]])

In [126]:
# Perform a dot product on the two newest arrays you created
np.dot(a13_random, a14_random)

array([[ 44,  65],
       [126, 167],
       [ 58,  81]])

In [127]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(0)
a15_random = np.random.randint(0,11,size=(4,3))
a16_random = np.random.randint(0,11,size=(4,3))

In [130]:
a15_random

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [131]:
a16_random

array([[ 8,  8, 10],
       [ 1,  6,  7],
       [ 7,  8,  1],
       [ 5,  9,  8]])

In [129]:
# Perform a dot product on the two newest arrays you created
np.dot(a15_random, a16_random.T)

array([[ 70,  26,  38,  49],
       [170, 108,  86, 150],
       [ 84,  47,  63,  76],
       [148,  88,  90, 131]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [132]:
# Compare the two arrays with '>'
a15_random > a16_random

array([[False, False, False],
       [ True,  True,  True],
       [False, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [133]:
# Compare the two arrays with '>='
a15_random >= a16_random

array([[False, False, False],
       [ True,  True,  True],
       [False, False,  True],
       [False, False, False]])

In [150]:
a15_random

array([[0, 3, 5],
       [3, 7, 9],
       [2, 3, 5],
       [4, 6, 7]])

In [134]:
# Find which elements of the first array are greater than 7
a15_random > 7

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [137]:
a16_random

array([[ 8,  8, 10],
       [ 1,  6,  7],
       [ 7,  8,  1],
       [ 5,  9,  8]])

In [136]:
# Which parts of each array are equal? (try using '==')
a15_random == a16_random

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [147]:
# Sort one of the arrays you just created in ascending order
a15_random.sort()
a15_random

array([[0, 3, 5],
       [3, 7, 9],
       [2, 3, 5],
       [4, 6, 7]])

In [144]:
# Sort the indexes of one of the arrays you just created
np.argsort(a15_random)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [145]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a15_random)

5

In [146]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a15_random)

0

In [148]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a15_random,axis=1)

array([2, 2, 2, 2], dtype=int64)

In [149]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(a15_random,axis=0)

array([3, 1, 1], dtype=int64)

In [155]:
# Create an array of normally distributed random numbers

# Parameters:
# locfloat or array_like of floats
# Mean (“centre”) of the distribution.

# scalefloat or array_like of floats
# Standard deviation (spread or “width”) of the distribution. Must be non-negative.

# sizeint or tuple of ints, optional
# Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if loc and scale are both scalars. Otherwise, np.broadcast(loc, scale).size samples are drawn.

# Returns:
# outndarray or scalar
# Drawn samples from the parameterized normal distribution.

np.random.normal(3,2.5,size=(5,5))

array([[ 4.59933999,  2.03534166,  1.06059412,  5.48927837, -1.83301195],
       [ 3.62132657,  2.92188666,  2.65131509,  2.52336005,  4.12159382],
       [ 0.51892557,  2.43515086, -1.13642692,  1.40069341,  1.8014505 ],
       [ 3.77840876,  1.05994883,  2.23158797,  2.08369015,  5.79927991],
       [ 1.85519395,  4.0634835 ,  2.93007204,  6.68997458,  4.61695024]])

In [158]:
np.random.randn(3, 5)

array([[-0.36433431, -0.67877739, -0.35362786, -0.74074747, -0.67502183],
       [-0.13278426,  0.61980106,  1.79116846,  0.17100044, -1.72567135],
       [ 0.16065854, -0.85898532, -0.20642094,  0.48842647, -0.83833097]])

In [156]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [157]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.